[tool.mypy]
# Global options:
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
allow_untyped_calls = false
allow_untyped_defs = false
check_untyped_defs = true
show_error_codes = true
